<?php

/* User profile form alter */
function tch_form_user_profile_form_alter(&$form, &$form_state, $form_id){
	
	$form['field_user_follow']['#type'] = "hidden";
	$form['field_user_edit']['#type'] = "hidden";	
	
}

/* User login form alter */
function tch_form_user_login_alter(&$form, &$form_state) {
//	dsm($form);
	
	$form['rpx_links']['#title'] = "Sign up / Log in using one of these accounts";
	
  	$form['login_title'] = array(
		'#theme' => 'item_list',
    	'#weight' => -140,
		'#title' => "Log in with username and password",
  	);	

	$form['actions']['submit']['#suffix'] = '<br /><a href="user/register">Create new account</a> | <a href="/user/password">Request new password</a>';
	
	
}

/* Location form alter */
function tch_form_location_node_form_alter(&$form, &$form_state, $form_id){

//	dsm($form);
	
	$query = drupal_get_query_parameters();
	
	if(@$query[field_search_value]) $form['field_title'][$form['field_title']['#language']][0]['value']['#default_value'] = @$query[field_search_value];
	
	//Google map
	drupal_add_js("http://maps.google.com/maps/api/js?libraries=places&sensor=false&region=AU", "external");	
	drupal_add_js(drupal_get_path('module', 'tch') .'/geolocation.js');
	
	$form['field_country']['#suffix'] = "<div class='map'><label>Not the right location on map? Drag the pin to update it.</label><div id='create-location-map' style='width: 426px; height: 300px'></div></div>";

	drupal_add_css("sites/travellingchair.net/themes/tchair/admin.css");

	/**
	 * Multi-columns settings
	 */
	//category
	$form['field_category'][$form['field_category']['#language']]['#multicolumn'] = array('width' => 4);      
	
	//place to eat
	$form['field_place_to_eat'][$form['field_place_to_eat']['#language']]['#multicolumn'] = array('width' => 5);	  
	//out for the evening
	$form['field_evening_out'][$form['field_evening_out']['#language']]['#multicolumn'] = array('width' => 5);  
	//retail outlets
	$form['field_retail_outlets'][$form['field_retail_outlets']['#language']]['#multicolumn'] = array('width' => 5);
	//Entertainment
	$form['field_entertainment'][$form['field_entertainment']['#language']]['#multicolumn'] = array('width' => 5);
	//Sports/Leisure
	$form['field_sports_leisure'][$form['field_sports_leisure']['#language']]['#multicolumn'] = array('width' => 2);
	//Health/Medica
	$form['field_health_medical'][$form['field_health_medical']['#language']]['#multicolumn'] = array('width' => 5);
	//Accommodation/Tourism
	$form['field_accommodation_tourism'][$form['field_accommodation_tourism']['#language']]['#multicolumn'] = array('width' => 5);
	//Education/Childcare
	$form['field_education_childcare'][$form['field_education_childcare']['#language']]['#multicolumn'] = array('width' => 5);
	//Other
	$form['field_other'][$form['field_other']['#language']]['#multicolumn'] = array('width' => 5);
	//Transport
	$form['field_transport'][$form['field_transport']['#language']]['#multicolumn'] = array('width' => 5);
	//Event Hire Venues
	$form['field_event_hire_venues'][$form['field_event_hire_venues']['#language']]['#multicolumn'] = array('width' => 5);
	//General Shopping
	$form['field_general_shopping'][$form['field_general_shopping']['#language']]['#multicolumn'] = array('width' => 5);

	//Hide rating fields and set default values
	$form['field_visual']['und'][0]['value']['#default_value'] = 0;
	$form['field_visual']['und'][0]['value']['#type'] = "hidden";
	$form['field_hearing']['und'][0]['value']['#default_value'] = 0;
	$form['field_hearing']['und'][0]['value']['#type'] = "hidden";
	$form['field_mobility']['und'][0]['value']['#default_value'] = 0;
	$form['field_mobility']['und'][0]['value']['#type'] = "hidden";
			
	$form['field_visual_bar']['und'][0]['value']['#default_value'] = 0;
	$form['field_visual_bar']['und'][0]['value']['#type'] = "hidden";
	$form['field_hearing_bar']['und'][0]['value']['#default_value'] = 0;
	$form['field_hearing_bar']['und'][0]['value']['#type'] = "hidden";
	$form['field_mobility_bar']['und'][0]['value']['#default_value'] = 0;
	$form['field_mobility_bar']['und'][0]['value']['#type'] = "hidden";		

	$form['field_rates_for_sort']['und'][0]['value']['#type'] = "hidden";		


	/**
	 * Hide fields
	 */
	//Hide review now
	$form['field_review_now']['und'][0]['value']['#type'] = "hidden";
	
	//Hide search
	$form['field_search']['und'][0]['value']['#type'] = "hidden";
	

	//Hide all widgets
	$widgets = rate_get_active_widgets('node', 'location');
	
	for ($i=1; $i<=count($widgets)+1; $i++){	
		if (@$form['field_widget'.$i]){
//			$form['field_widget'.$i]['und'][0]['value']['#default_value'] = 0;	
			$form['field_widget'.$i]['und'][0]['value']['#type'] = "hidden";		
		}
	}
	
	//Hide Longitude and Latitude fields
//	$form['field_latitude']['und'][0]['value']['#type'] = "hidden";
//	$form['field_longitude']['und'][0]['value']['#type'] = "hidden";
	
	//Hide edit field
	$form['field_edit']['und'][0]['value']['#default_value'] = "edit venue";
	$form['field_edit']['#type'] = "hidden";
	
	//Hide view result
	$form['field_view_result']['und'][0]['value']['#type'] = "hidden";	
	
	//Hide sharethis
	$form['field_sharethis']['und'][0]['value']['#type'] = "hidden";	
	
//dsm($form);
}


function tch_node_update($node){

	// Set all widgets to 0 only if it is updated in admin/content
	if ($node->type == "location" && arg(0) == 'admin' && arg(1)=='content') {
		$widgets = rate_get_active_widgets('node', 'location');
	
		for ($i=1; $i<=count($widgets)+1; $i++){						
			if (property_exists($node, 'field_widget'.$i)){

				 db_update('field_data_field_widget'.$i)
				 ->fields(array(
				  'field_widget'.$i.'_value' => 0,
				 ))
				 ->condition('entity_id', $node->nid, '=')
				 ->execute();
			}
		}
		
	}

	
}

function tch_node_presave($node){

	@$search[] = $node->title;	
	@$search[] = $node->field_address[und][0][value];
	@$search[] = $node->field_city[und][0][value];
	@$search[] = $node->field_state[und][0][value];
	@$search[] = $node->field_postcode[und][0][value];
	@$search[] = $node->locations[0][country_name];	
	
	
	@$node->field_search[und][0][value] = implode(' ', $search);
}

function tch_node_view($node, $view_mode, $langcode){
	if ($node->type == "location" && $view_mode=="full"){
		$widgets = rate_get_active_widgets('node', 'location');
		foreach ($widgets as $key=>$widget) {
			$votingapi_results = votingapi_select_results(array(
			  'entity_type' => 'node',
			  'entity_id' => $node->nid,
			  'tag' => $widget->tag,
			  'value_type' => $widget->value_type,
			));
		//dsm($votingapi_results);
			$up=0; $down=0;
			foreach ($votingapi_results as $votingapi_result){
				if ($votingapi_result['function'] == 'option-1') $up = @$votingapi_result['value'];
				if ($votingapi_result['function'] == 'option--1') $down = @$votingapi_result['value'];
			}
//			@$node->{field_widget.$key}['und'][0]['value'] = 0;
//			if ($up+$down > 0){
//				@$node->{field_widget.$key}['und'][0]['value'] = $up/($up+$down);
//			}
			//dsm($up/($up+$down));
		
			if($node->{field_widget.$key}['und'][0]['value'] != $up/($up+$down)){
				db_update('field_data_field_widget'.$key)
			        ->fields(array('field_widget'.$key.'_value' => $up/($up+$down)))
			        ->condition('entity_id', $node->nid)
			        ->execute();

			}
		}
		

	}
}

function tch_node_insert($node){
	$query = array("action"=>"review");
	drupal_goto('node/'.$node->nid, array("query"=>$query));
}

function tch_form_views_exposed_form_alter(&$form, $form_state, $form_id) {

	$query = drupal_get_query_parameters();
	
	switch ($form['#id']) {
		//Search Review
		case "views-exposed-form-search-page":
//			dsm ($form);

		break;
		
		//Create Review
		case "views-exposed-form-search-page-2":
//			dsm ("Create Review");
		break;
	}
	
}

function tch_search_validation (){
	views_exposed_form_validate();
}

/*
 * Creates a star rating based on total votes and up/good votes
 */
function tch_star_rating($total, $good) {
	$maxStars = 5;
	
	$output = '';
	$stars = $good / $total * $maxStars;
	$stars = floor( $stars * 2 ) / 2;

	for ($i=0.5; $i < $stars; $i++) {
	  $output .= '<span class="full">★</span>';
	}
	if ( is_numeric( $stars ) && floor( $stars ) != $stars ) $output.= '<span class="half">★</span>';

	for ($i=$stars + 0.5; $i < $maxStars; $i++) {
	  $output .= '<span class="empty">☆</span>';
	}

	if ($total == 1)
		$plural = '';
	else 
		$plural = 's';

	$output .= ' <span class="total-votes">(' . $total . ' rating' . $plural . ')</span>';

	return $output;
}